### ISSUE TITLE
Pipenv vs pip

### ISSUE THREAD

**Issue by adnathanail** [testdrivenio/django-on-docker#15]
Hi, sorry  if this is the wrong place to do this, but could you explain why you switched from Pipenv to Pip for this repo and the accompanying tutorial?

Many thanks,

Alex

**Comment by mjhea0** [comment]
Dependency resolution is too slow.

https://www.reddit.com/r/django/comments/diqo6g/dockerizing_django_with_postgres_gunicorn_and/f3y63l6/

**Comment by adnathanail** [comment]
Thanks!
