### ISSUE TITLE
Additional issues with Certbot?

### ISSUE THREAD

**Issue by eolach** [testdrivenio/django-on-docker#2]
There appear to be additional considerations when adding encryption to support https access. Is this addressed elsewhere in your (excellent) work?

**Comment by mjhea0** [comment]
Apologies for the late response, @eolach. You would want to set up SSL/TLS to secure Nginx.

https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71

**Comment by eolach** [comment]
Thanks.
