### ISSUE TITLE
Conflict between dev and prod

### ISSUE THREAD

**Issue by mflage** [testdrivenio/django-on-docker#30]
Hi!

I'm trying to make sense on the different containers built here and the relation between them. It seems like there is a conflict between the database and web for the two environments? If I build the prod compose first, then that db will be prevalent. So if I then try to bring up the development stack before the production stack, then the database will be "stuck" as the development one. There doesn't seem like these two stacks can co-exist?

**Comment by mjhea0** [comment]
No, they aren't mean to co-exist. If you want them to, change the name of the volume for one of them. `postgres_data_prod`, for example.
