### ISSUE TITLE
Please mention the database flush in the Readme

### ISSUE THREAD

**Issue by dipanghosh** [testdrivenio/django-on-docker#41]
Hi,

I was using your nice setup for building a django project. I am absolutely new to django, but I have experience with Docker, so I am trying to do this containerized. Your setup was pretty much exactly what I was looking for, so I adopted it.

I got it working, but there was a frustrating half hour of me not understanding why the database wont persist, despite the docker volume setup. I overlooked the flush command in the bash file, but eventually managed to track it down. 

Perhaps that makes sense in the setup, but please add a section in the readme here on the page explaining that on restarting the container, the database is wiped clean.

Thank you for making this available.

**Comment by NikitaKozlovtcev** [comment]
It was explain there https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
