### ISSUE TITLE
Copy overrides entrypoint.sh

### ISSUE THREAD

**Issue by pisarik** [testdrivenio/django-on-docker#43]
This will override entrypoint.sh, isn't it?

https://github.com/testdrivenio/django-on-docker/blob/ce7c04cc14c95fa29799e2d40d6bdbdb5554f7c4/app/Dockerfile#L20-L26

**Comment by pisarik** [comment]
Looks that `COPY . .` is unnecessary at all, since the folder will be mounted anyway (i.e. volumes option in compose config)

**Comment by maxiller** [comment]
Well, it seems lima is causing this behaviour, eventually... 
The daemon inside it executes instructions from compose file that order mounting a path, it executes it, but that path obviously does not exist in the lima's vm.
Going to try out some other alternative to docker desktop.

**Comment by mod64bits** [comment]
I'm having a permission error on entrypoint.prod.sh
container process: exec: "/home/app/web/entrypoint.prod.sh": permission denied: unknown

**Comment by AdejohOS** [comment]
@mod64bits, I have been getting same permission error when i try to add the configuration to my own project. I honestly don't know what the problem is.

**Comment by SaraFarron** [comment]
For those who get `permission denied: unknown`
change `entrypoint.sh` or `entrypoint.prod.sh` like
```
# copy entrypoint.sh
# COPY ./entrypoint.sh .

# copy project
COPY . .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh
```
so that file is copied and then permissions applied

**Comment by Tealk** [comment]
doesn't really work for me

```
STEP 10/15: COPY . .
--> 600637e90b7f
STEP 11/15: RUN dos2unix /usr/src/app/entrypoint.sh
dos2unix: converting file /usr/src/app/entrypoint.sh to Unix format...
--> e19631157729
STEP 12/15: RUN chmod +x /usr/src/app/entrypoint.sh
--> e246381465b1
STEP 13/15: RUN ls -l /usr/src/app/entrypoint.sh
-rwxr-xr-x. 1 root root 196 Aug 10 10:51 /usr/src/app/entrypoint.sh
--> f937d257cc15
STEP 14/15: RUN cat /usr/src/app/entrypoint.sh
#!/bin/sh

echo "Waiting for postgres..."

while ! nc -z $SQL_HOST $SQL_PORT; do
  sleep 0.1
done

echo "PostgreSQL started"

python manage.py flush --no-input
python manage.py migrate

exec "$@"
--> ce55062fa82d
STEP 15/15: ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
```

web-1:
```
/bin/sh: 0: cannot open /usr/src/app/entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /usr/src/app/entrypoint.sh: Permission denied
```

i had to add a `:z` to the end of the path
https://github.com/testdrivenio/django-on-docker/blob/main/docker-compose.yml#L8

**Comment by ghost** [comment]
I don't think any copy is needed because of this bind mount.

Instead of adding execute permissions on that file I just run it like this:
```
ENTRYPOINT ["/bin/bash", "/usr/src/app/entrypoint.sh"]
```
