### ISSUE TITLE
Debug Flag as bool 

### ISSUE THREAD

**Issue by onskateboard** [testdrivenio/django-on-docker#50]
Error because debug flag gots interpreted only as bool not int (Version: Django 3.2.7)

in settings.py, line 26
change: DEBUG = int(os.environ.get("DEBUG", default=0))
to: DEBUG = bool(os.environ.get("DEBUG", default=0))

**Comment by 954-Ivory** [comment]
This PR is error.
When we set the `DEBUG=0` in envs file, we will get a `str` type: `'0'`.
```python
bool(os.environ.get("DEBUG", '0')) # This will be `True`
```
So, we need change it to:
```python
bool(int(os.environ.get("DEBUG", default=0)))
```
