### ISSUE TITLE
Entrypoint script not found

### ISSUE THREAD

**Issue by jkariscodes** [testdrivenio/django-on-docker#54]
Hi. Been following your tutorial [here](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/) and encountering the issue that the **entrypoint.sh** cannot be found.

`django-nginx-docker-web-1  | exec /usr/src/app/entrypoint.sh: no such file or directory`

**Comment by jagobrown** [comment]
FYI

I've got a near identical error:

> exec /home/app/web/entrypoint.prod.sh: no such file or directory

I'm running on Docker Desktop for Windows & have just cloned this github repo, removed trailing `-sample` from the 2 production .env file names and run

docker-compose -f docker-compose.prod.yml up -d --build

Postgres builds and runs but web exits & logs:

> exec /home/app/web/entrypoint.prod.sh: no such file or directory

I'm look at this again when more time

**Comment by shenzhongling** [comment]
windows install docker 
docker setting
Expose daemon on tcp://localhost:2375 without TLS
select
